
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SampleWebService", targetNamespace = "http://ws.wsexamples.javaee.todomvc.ondrej.mihalyi/", wsdlLocation = "http://localhost:8080/todomvc-javaee/SampleWebService?WSDL")
public class SampleWebService_Service
    extends Service
{

    private final static URL SAMPLEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAMPLEWEBSERVICE_EXCEPTION;
    private final static QName SAMPLEWEBSERVICE_QNAME = new QName("http://ws.wsexamples.javaee.todomvc.ondrej.mihalyi/", "SampleWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/todomvc-javaee/SampleWebService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAMPLEWEBSERVICE_WSDL_LOCATION = url;
        SAMPLEWEBSERVICE_EXCEPTION = e;
    }

    public SampleWebService_Service() {
        super(__getWsdlLocation(), SAMPLEWEBSERVICE_QNAME);
    }

    public SampleWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAMPLEWEBSERVICE_QNAME, features);
    }

    public SampleWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SAMPLEWEBSERVICE_QNAME);
    }

    public SampleWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAMPLEWEBSERVICE_QNAME, features);
    }

    public SampleWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SampleWebService
     */
    @WebEndpoint(name = "SampleWebServicePort")
    public SampleWebService getSampleWebServicePort() {
        return super.getPort(new QName("http://ws.wsexamples.javaee.todomvc.ondrej.mihalyi/", "SampleWebServicePort"), SampleWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleWebService
     */
    @WebEndpoint(name = "SampleWebServicePort")
    public SampleWebService getSampleWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wsexamples.javaee.todomvc.ondrej.mihalyi/", "SampleWebServicePort"), SampleWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAMPLEWEBSERVICE_EXCEPTION!= null) {
            throw SAMPLEWEBSERVICE_EXCEPTION;
        }
        return SAMPLEWEBSERVICE_WSDL_LOCATION;
    }

}
